#!/bin/bash

if [ -z "$NVM_DIR" ]
then
NVM_DIR="$HOME/.nvm"
fi

. $NVM_DIR/nvm.sh
nvm install
nvm use

set -e

if hash pyenv 2>/dev/null;
then
  echo "using pyenv wrapper"
  pyenv install --skip-existing
  pyenv exec pyvenv env
else
  echo "using pyvenv (Built in python)"
  pyvenv env
fi

export PATH=env/bin:${PATH}

pip install -r requirements.txt

npm install
npm run build

honcho --app-root etc/environments/development --env env run env/bin/python manage.py collectstatic --noinput
